export default  {
        Server: Symbol("Server"),
        Application: Symbol("Application"),
        DifferenceGeneratorService: Symbol("DifferenceGeneratorService"),
        UserService: Symbol("UserService"),
        UserController: Symbol("UserController"),
        SocketService: Symbol("SocketService"),
        ImageValidationService: Symbol("ImageValidationService"),
        GameService: Symbol("GameService"),
        GameController: Symbol("GameController"),
        ImageService: Symbol("ImageService"),
        ImageController: Symbol("ImageController"),
        IdentificationService: Symbol("IdentificationService"),
        Identification3DService: Symbol("Identification3DService"),
        IdentificationController: Symbol("IdentificationController"),
        BestScoreService: Symbol("BestScoreService"),
        DuoGameService: Symbol("DuoGameService"),
        SocketEmitterService: Symbol("SocketEmitterService"),
        OnGoingGameService: Symbol("OnGoingGameService"),
};
