export enum SocketEvent {
    CONNECT = "connect",
    DISCONNECT = "disconnect",
    NEW_USER = "newUser",
    NEW_MESSAGE = "newMessage",
    NEW_DUO_PLAYER = "newDuoPlayer",
    REMOVE_GAME = "removeGame",
    RESET_SCORES = "resetScores",
    CREATE_DUO_GAME = "createDuoGame",
    JOIN_DUO_GAME = "joinDuoGame",
    LEAVE_DUO_GAME = "leaveDuoGame",
    SIMPLE_DIFFERENCE_FOUND = "simpleDifferenceFound",
    FREE_DIFFERENCE_FOUND = "freeDifferenceFound",
    NEW_SCORE = "newScore",
    UPDATE_SIMPLE_GAMES = "updateSimpleGames",
    UPDATE_FREE_GAMES = "updateFreeGames",
    UPDATE_SIMPLE_GAME = "updateSimpleGame",
    UPDATE_FREE_GAME = "updateFreeGame",
    NEW_SIMPLE_GAME = "newSimpleGame",
    NEW_FREE_GAME = "newFreeGame",
    END_DUO_GAME = "endDuoGame",
    NEW_ON_GOING_GAME = "newOnGoingGame",
    REMOVE_ON_GOING_GAME = "removeOnGoingGame",

    UPDATE_SIMPLE_GAME_STATE = "updateSimpleGameState",
    UPDATE_FREE_GAME_STATE = "updateFreeGameState",
    QUIT_DUO_GAME = "quitDuoGame",
}